// Auto-generated from Shopee's official Biaya Administrasi table (Non-Star).
// Admin fee percentages per product category. Used to quick-fill the
// Admin rate in the fee profile. You can override this live via a
// published Google Sheet CSV (see loadFeeCategories).
export interface FeeCategory { main: string; label: string; pct: number }
export const FEE_CATEGORIES: FeeCategory[] = [
  { main: "Fashion", label: "Aksesoris Fashion — Aksesoris Rambut", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Aksesoris Tambahan", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Anting", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Cincin", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Dasi", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Gelang Kaki", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Gelang Tangan & Bangle", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Ikat Pinggang", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Kacamata & Aksesoris", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Kalung", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Sarung Tangan", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Set & Paket Aksesoris", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Syal & Selendang", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Topi", pct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Aksesoris Tambahan", pct: 8.25 },
  { main: "Fashion", label: "Aksesoris Fashion — Logam Mulia", pct: 4.25 },
  { main: "Fashion", label: "Aksesoris Fashion — Perhiasan Berharga", pct: 4.25 },
  { main: "Fashion", label: "Aksesoris Fashion — Aksesoris Fashion Lainnya", pct: 9.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Aksesoris Bayi & Anak", pct: 9.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Pakaian Anak Laki-Laki", pct: 9.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Pakaian Anak Perempuan", pct: 9.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Pakaian Bayi", pct: 9.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Sepatu Anak Laki-Laki", pct: 9.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Sepatu Anak Perempuan", pct: 9.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Sepatu Bayi", pct: 9.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Aksesoris Bayi & Anak", pct: 4.25 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Fashion Bayi & Anak Lainnya", pct: 9.0 },
  { main: "Fashion", label: "Fashion Muslim — Pakaian Muslim Wanita", pct: 10.0 },
  { main: "Fashion", label: "Fashion Muslim — Mukena & Perlengkapan Sholat", pct: 8.25 },
  { main: "Fashion", label: "Fashion Muslim — Outerwear", pct: 8.25 },
  { main: "Fashion", label: "Fashion Muslim — Pakaian Muslim Anak", pct: 8.25 },
  { main: "Fashion", label: "Fashion Muslim — Pakaian Muslim Pria", pct: 8.25 },
  { main: "Fashion", label: "Fashion Muslim — Pakaian Muslim Wanita", pct: 8.25 },
  { main: "Fashion", label: "Fashion Muslim — Set", pct: 8.25 },
  { main: "Fashion", label: "Fashion Muslim — Fashion Muslim Lainnya", pct: 8.25 },
  { main: "Fashion", label: "Jam Tangan — Aksesoris Jam Tangan", pct: 9.0 },
  { main: "Fashion", label: "Jam Tangan — Jam Tangan Couple", pct: 9.0 },
  { main: "Fashion", label: "Jam Tangan — Jam Tangan Pria", pct: 9.0 },
  { main: "Fashion", label: "Jam Tangan — Jam Tangan Wanita", pct: 9.0 },
  { main: "Fashion", label: "Jam Tangan — Jam Tangan Lainnya", pct: 9.0 },
  { main: "Fashion", label: "Koper & Tas Travel — Tas Travel", pct: 10.0 },
  { main: "Fashion", label: "Koper & Tas Travel — Aksesoris Travel", pct: 9.0 },
  { main: "Fashion", label: "Koper & Tas Travel — Koper", pct: 9.0 },
  { main: "Fashion", label: "Koper & Tas Travel — Tas Travel", pct: 9.0 },
  { main: "Fashion", label: "Koper & Tas Travel — Koper & Tas Travel Lainnya", pct: 9.0 },
  { main: "Fashion", label: "Pakaian Pria — Kaos Kaki", pct: 10.0 },
  { main: "Fashion", label: "Pakaian Pria — Atasan", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Celana Panjang", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Celana Panjang Jeans", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Celana Pendek", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Hoodie & Sweatshirt", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Jaket, Mantel, & Rompi", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Jas Formal", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Kostum", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Pakaian Dalam", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Pakaian Kerja", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Pakaian Tidur", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Pakaian Tradisional", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Set Pakaian Pria", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Sweater & Cardigan", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Pria — Pakaian Pria Lainnya", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Kaos Kaki & Stocking", pct: 10.0 },
  { main: "Fashion", label: "Pakaian Wanita — Kaos Kaki & Stocking", pct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Atasan", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Baju Hamil", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Celana Jeans", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Celana Panjang & Legging", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Celana Pendek", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Dress", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Hoodie & Sweatshirt", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Jaket, Mantel, & Rompi", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Jumpsuit, Playsuit, & Overall", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Kain", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Kostum", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Pakaian Dalam", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Pakaian Tidur & Piyama", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Pakaian Tradisional", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Rok", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Set", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Sweater & Cardigan", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Wedding Dress", pct: 8.25 },
  { main: "Fashion", label: "Pakaian Wanita — Pakaian Wanita Lainnya", pct: 8.25 },
  { main: "Fashion", label: "Sepatu Pria — Aksesoris & Perawatan Sepatu", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Pria — Boot", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Pria — Loafer", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Pria — Oxford", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Pria — Sandal", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Pria — Slip-On & Mules", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Pria — Sneakers", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Pria — Sepatu Pria Lainnya", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Wanita — Aksesoris & Perawatan Sepatu", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Wanita — Boots", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Wanita — Heels", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Wanita — Sandal Jepit & Sandal Lainnya", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Wanita — Sepatu Flat", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Wanita — Sneakers", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Wanita — Wedges", pct: 9.0 },
  { main: "Fashion", label: "Sepatu Wanita — Sepatu Wanita Lainnya", pct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Clutch", pct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Dompet", pct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Ransel Pria", pct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tas Kerja", pct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tas Laptop", pct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tas Pinggang Pria", pct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tas Selempang & Bahu Pria", pct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tote Bag", pct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tas Pria Lainnya", pct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Aksesoris Tas", pct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Clutch", pct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Dompet Wanita", pct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Ransel Wanita", pct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Tas Laptop", pct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Tas Pinggang Wanita", pct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Tas Selempang & Bahu Wanita", pct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Top Handle Bag", pct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Tote Bag", pct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Tas Wanita Lainnya", pct: 9.0 },
  { main: "FMCG", label: "Ibu & Bayi — Mainan", pct: 10.0 },
  { main: "FMCG", label: "Ibu & Bayi — Keamanan Bayi", pct: 9.5 },
  { main: "FMCG", label: "Ibu & Bayi — Kesehatan Kehamilan", pct: 9.5 },
  { main: "FMCG", label: "Ibu & Bayi — Mainan", pct: 9.5 },
  { main: "FMCG", label: "Ibu & Bayi — Perlengkapan Ibu Hamil", pct: 9.5 },
  { main: "FMCG", label: "Ibu & Bayi — Perlengkapan Makan Bayi", pct: 9.5 },
  { main: "FMCG", label: "Ibu & Bayi — Perlengkapan Travelling Bayi", pct: 9.5 },
  { main: "FMCG", label: "Ibu & Bayi — Popok & Pispot", pct: 9.0 },
  { main: "FMCG", label: "Ibu & Bayi — Kamar Bayi", pct: 8.25 },
  { main: "FMCG", label: "Ibu & Bayi — Kesehatan Bayi", pct: 8.25 },
  { main: "FMCG", label: "Ibu & Bayi — Mainan", pct: 8.25 },
  { main: "FMCG", label: "Ibu & Bayi — Perlengkapan Makan Bayi", pct: 8.25 },
  { main: "FMCG", label: "Ibu & Bayi — Perlengkapan Mandi", pct: 8.25 },
  { main: "FMCG", label: "Ibu & Bayi — Set & Paket Hadiah", pct: 8.25 },
  { main: "FMCG", label: "Ibu & Bayi — Susu Formula & Makanan Bayi", pct: 6.75 },
  { main: "FMCG", label: "Ibu & Bayi — Kesehatan Bayi", pct: 6.5 },
  { main: "FMCG", label: "Ibu & Bayi — Ibu & Bayi Lainnya", pct: 8.25 },
  { main: "FMCG", label: "Kesehatan — Perawatan Diri", pct: 10.0 },
  { main: "FMCG", label: "Kesehatan — Obat-obatan & Alat Kesehatan", pct: 9.5 },
  { main: "FMCG", label: "Kesehatan — Perawatan Diri", pct: 9.5 },
  { main: "FMCG", label: "Kesehatan — Kesehatan Seksual", pct: 9.0 },
  { main: "FMCG", label: "Kesehatan — Obat-obatan & Alat Kesehatan", pct: 9.0 },
  { main: "FMCG", label: "Kesehatan — Perawatan Diri", pct: 9.0 },
  { main: "FMCG", label: "Kesehatan — Suplemen Makanan", pct: 9.0 },
  { main: "FMCG", label: "Kesehatan — Kesehatan Lainnya", pct: 9.0 },
  { main: "FMCG", label: "Makanan & Minuman — Makanan Ringan", pct: 10.0 },
  { main: "FMCG", label: "Makanan & Minuman — Makanan Ringan", pct: 9.5 },
  { main: "FMCG", label: "Makanan & Minuman — Bahan Pokok", pct: 9.5 },
  { main: "FMCG", label: "Makanan & Minuman — Minuman", pct: 9.5 },
  { main: "FMCG", label: "Makanan & Minuman — Minuman Alkohol", pct: 9.5 },
  { main: "FMCG", label: "Makanan & Minuman — Set Hadiah & Hampers", pct: 9.5 },
  { main: "FMCG", label: "Makanan & Minuman — Makanan Instan", pct: 9.0 },
  { main: "FMCG", label: "Makanan & Minuman — Roti & Kue", pct: 9.0 },
  { main: "FMCG", label: "Makanan & Minuman — Susu & Olahan", pct: 8.25 },
  { main: "FMCG", label: "Makanan & Minuman — Bahan Baking", pct: 6.75 },
  { main: "FMCG", label: "Makanan & Minuman — Bahan Pokok", pct: 6.75 },
  { main: "FMCG", label: "Makanan & Minuman — Kebutuhan Memasak", pct: 6.75 },
  { main: "FMCG", label: "Makanan & Minuman — Makanan Segar & Beku", pct: 6.75 },
  { main: "FMCG", label: "Makanan & Minuman — Menu Sarapan", pct: 6.75 },
  { main: "FMCG", label: "Makanan & Minuman — Susu & Olahan", pct: 6.75 },
  { main: "FMCG", label: "Makanan & Minuman — Susu & Olahan", pct: 6.5 },
  { main: "FMCG", label: "Makanan & Minuman — Makanan & Minuman Lainnya", pct: 9.5 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Alat Kecantikan", pct: 8.25 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Kosmetik", pct: 8.25 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Paket & Set Kecantikan", pct: 8.25 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Parfum & Wewangian", pct: 8.25 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan Pria", pct: 8.25 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan Rambut", pct: 8.25 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan Tangan, Kaki & Kuku", pct: 8.25 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan Tubuh", pct: 8.25 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan Wajah", pct: 8.25 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan & Kecantikan Lainnya", pct: 8.25 },
  { main: "Elektronik", label: "Audio — Media Player", pct: 9.5 },
  { main: "Elektronik", label: "Audio — Amplifier & Mixer", pct: 9.0 },
  { main: "Elektronik", label: "Audio — Kabel & Konverter Audio & Video", pct: 9.0 },
  { main: "Elektronik", label: "Audio — Mikrofon & Aksesoris", pct: 9.0 },
  { main: "Elektronik", label: "Audio — Perangkat Audio & Speaker", pct: 9.0 },
  { main: "Elektronik", label: "Audio — Earphone, Headphone, & Headset", pct: 6.75 },
  { main: "Elektronik", label: "Audio — Audio Lainnya", pct: 9.0 },
  { main: "Elektronik", label: "Elektronik — Kelistrikan", pct: 10.0 },
  { main: "Elektronik", label: "Elektronik — Baterai", pct: 9.5 },
  { main: "Elektronik", label: "Elektronik — Peralatan Listrik Besar", pct: 9.5 },
  { main: "Elektronik", label: "Elektronik — Peralatan Listrik Kecil", pct: 9.5 },
  { main: "Elektronik", label: "Elektronik — Peralatan Listrik Besar", pct: 9.0 },
  { main: "Elektronik", label: "Elektronik — Peralatan Listrik Kecil", pct: 9.0 },
  { main: "Elektronik", label: "Elektronik — Remot Kontrol", pct: 9.0 },
  { main: "Elektronik", label: "Elektronik — Rokok Elektronik & Shisha", pct: 9.0 },
  { main: "Elektronik", label: "Elektronik — Peralatan Listrik Besar", pct: 6.5 },
  { main: "Elektronik", label: "Elektronik — Peralatan Listrik Kecil", pct: 6.5 },
  { main: "Elektronik", label: "Elektronik — Perangkat Dapur", pct: 6.5 },
  { main: "Elektronik", label: "Elektronik — TV & Aksesoris", pct: 6.5 },
  { main: "Elektronik", label: "Elektronik — Proyektor & Aksesoris", pct: 5.25 },
  { main: "Elektronik", label: "Elektronik — Elektronik Lainnya", pct: 9.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Konsol Game", pct: 9.5 },
  { main: "Elektronik", label: "Gaming & Konsol — Video Game", pct: 9.5 },
  { main: "Elektronik", label: "Gaming & Konsol — Aksesoris Konsol", pct: 9.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Gaming & Konsol Lainnya", pct: 9.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Aksesoris", pct: 10.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Perangkat Wearable", pct: 10.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Aksesoris", pct: 9.5 },
  { main: "Elektronik", label: "Gaming & Konsol — Perangkat Wearable", pct: 9.5 },
  { main: "Elektronik", label: "Gaming & Konsol — Aksesoris", pct: 9.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Kartu Perdana", pct: 9.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Walkie Talkie", pct: 9.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Aksesoris", pct: 6.75 },
  { main: "Elektronik", label: "Gaming & Konsol — Handphone", pct: 5.25 },
  { main: "Elektronik", label: "Gaming & Konsol — Tablet", pct: 5.25 },
  { main: "Elektronik", label: "Gaming & Konsol — Handphone & Aksesoris Lainnya", pct: 10.0 },
  { main: "Elektronik", label: "Kamera & Drone — Aksesoris Kamera", pct: 9.5 },
  { main: "Elektronik", label: "Kamera & Drone — Kamera Keamanan", pct: 9.5 },
  { main: "Elektronik", label: "Kamera & Drone — Perawatan Kamera", pct: 9.5 },
  { main: "Elektronik", label: "Kamera & Drone — Aksesoris Drone", pct: 6.5 },
  { main: "Elektronik", label: "Kamera & Drone — Aksesoris Kamera", pct: 6.5 },
  { main: "Elektronik", label: "Kamera & Drone — Aksesoris Lensa", pct: 6.5 },
  { main: "Elektronik", label: "Kamera & Drone — Drone", pct: 6.5 },
  { main: "Elektronik", label: "Kamera & Drone — Kamera", pct: 6.5 },
  { main: "Elektronik", label: "Kamera & Drone — Lensa", pct: 6.5 },
  { main: "Elektronik", label: "Kamera & Drone — Kamera & Drone Lainnya", pct: 9.5 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Aksesoris Desktop & Laptop", pct: 6.75 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Keyboard & Mouse", pct: 6.75 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Komponen Network", pct: 6.75 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Software", pct: 6.75 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Komponen Desktop & Laptop", pct: 6.5 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Desktop", pct: 5.25 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Komponen Desktop & Laptop", pct: 5.25 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Laptop", pct: 5.25 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Monitor", pct: 5.25 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Penyimpanan Data", pct: 5.25 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Peralatan Kantor", pct: 5.25 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Printer & Scanner", pct: 5.25 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Komputer & Aksesoris Lainnya", pct: 6.75 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Perlengkapan Menggambar", pct: 10.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Pembungkus Kado & Kemasan", pct: 9.5 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Perlengkapan Sekolah & Kantor", pct: 9.5 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Alat Tulis", pct: 9.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Buku Tulis & Kertas", pct: 9.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Pembungkus Kado & Kemasan", pct: 9.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Perlengkapan Sekolah & Kantor", pct: 9.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Surat-Menyurat", pct: 9.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Buku & Alat Tulis Lainnya", pct: 10.0 },
  { main: "Lifestyle", label: "Buku & Majalah — Majalah & Koran", pct: 10.0 },
  { main: "Lifestyle", label: "Buku & Majalah — Buku Bacaan", pct: 9.5 },
  { main: "Lifestyle", label: "Buku & Majalah — Buku Bacaan", pct: 9.0 },
  { main: "Lifestyle", label: "Buku & Majalah — E-Book", pct: 9.0 },
  { main: "Lifestyle", label: "Buku & Majalah — Buku Bacaan", pct: 8.25 },
  { main: "Lifestyle", label: "Buku & Majalah — Buku & Majalah", pct: 9.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Aksesoris Hewan Peliharaan", pct: 9.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Grooming Hewan", pct: 9.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Litter & Toilet", pct: 9.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Makanan Hewan", pct: 9.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Pakaian & Aksesoris Hewan", pct: 9.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Perawatan Kesehatan Hewan", pct: 9.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Hewan Peliharaan Lainnya", pct: 9.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Alat & Aksesoris Musik", pct: 9.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Album Foto", pct: 9.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — CD, DVD & Bluray", pct: 9.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Koleksi", pct: 9.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Mainan & Games", pct: 9.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Perlengkapan Menjahit", pct: 9.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Piringan Hitam", pct: 9.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Souvenir & Hadiah", pct: 9.0 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Hobi & Koleksi Lainnya", pct: 9.5 },
  { main: "Lifestyle", label: "Mobil — Suku Cadang Mobil", pct: 9.5 },
  { main: "Lifestyle", label: "Mobil — Oli & Pelumas Kendaraan", pct: 9.0 },
  { main: "Lifestyle", label: "Mobil — Aksesoris Eksterior Mobil", pct: 8.25 },
  { main: "Lifestyle", label: "Mobil — Aksesoris Interior Mobil", pct: 8.25 },
  { main: "Lifestyle", label: "Mobil — Gantungan & Sarung Kunci Kendaraan", pct: 8.25 },
  { main: "Lifestyle", label: "Mobil — Perawatan Kendaraan", pct: 8.25 },
  { main: "Lifestyle", label: "Mobil — Perkakas & Perlengkapan Kendaraan", pct: 8.25 },
  { main: "Lifestyle", label: "Mobil — Mobil", pct: 2.5 },
  { main: "Lifestyle", label: "Mobil — Mobil Lainnya", pct: 8.25 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Aksesoris Olahraga & Aktivitas Outdoor", pct: 10.0 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Alat Rekreasi Olahraga & Aktivitas Outdoor", pct: 10.0 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Pakaian Olahraga & Aktivitas Outdoor", pct: 10.0 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Sepatu Olahraga", pct: 10.0 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Aksesoris Olahraga & Aktivitas Outdoor", pct: 8.25 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Olahraga & Outdoor Lainnya", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Alat Pengaman", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Alat Pertukangan & Renovasi Rumah", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Dekorasi", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Furniture", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Kamar Mandi", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Kamar Tidur", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Organizer Rumah", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Penghangat Tangan & Kantong Kompres", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Pengharum Ruangan & Aromaterapi", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Peralatan Makan", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perawatan Rumah", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perlengkapan Dapur", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perlengkapan Keagamaan", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Taman", pct: 10.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Lampu", pct: 9.5 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Dekorasi", pct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Furniture", pct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Pengharum Ruangan & Aromaterapi", pct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perawatan Rumah", pct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perlengkapan Pesta", pct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perlengkapan Dapur", pct: 6.5 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perlengkapan Rumah Lainnya", pct: 10.0 },
  { main: "Lifestyle", label: "Sepeda Motor — Aksesoris Sepeda Motor", pct: 8.25 },
  { main: "Lifestyle", label: "Sepeda Motor — Helm & Aksesoris Pengendara Motor", pct: 8.25 },
  { main: "Lifestyle", label: "Sepeda Motor — Suku Cadang Motor", pct: 8.25 },
  { main: "Lifestyle", label: "Sepeda Motor — Sepeda Motor", pct: 2.5 },
  { main: "Lifestyle", label: "Sepeda Motor — Sepeda Motor Lainnya", pct: 8.25 },
];
