// Auto-generated from Shopee's official 'Biaya Layanan Gratis Ongkir XTRA'
// table (Non-Star). Only applies if the seller has joined that program.
// Caps are fixed by Shopee: Rp40.000/item (Ukuran Biasa), Rp60.000/item
// (Ukuran Khusus) - see SERVICE_CAP_BIASA / SERVICE_CAP_KHUSUS below.
export interface ServiceFeeCategory { main: string; label: string; biasaPct: number; khususPct: number }
export const SERVICE_CAP_BIASA = 40000;
export const SERVICE_CAP_KHUSUS = 60000;
export const SERVICE_FEE_CATEGORIES: ServiceFeeCategory[] = [
  { main: "Elektronik", label: "Audio — Amplifier & Mixer", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Audio — Earphone, Headphone, & Headset", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Audio — Kabel & Konverter Audio & Video", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Audio — Media Player", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Audio — Mikrofon & Aksesoris", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Audio — Perangkat Audio & Speaker", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Audio — Audio Lainnya", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Elektronik — Proyektor & Aksesoris", biasaPct: 3.5, khususPct: 5.0 },
  { main: "Elektronik", label: "Elektronik — Baterai", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Elektronik — Peralatan Listrik Besar", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Elektronik — Peralatan Listrik Kecil", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Elektronik — Perangkat Dapur", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Elektronik — Remot Kontrol", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Elektronik — Rokok Elektronik & Shisha", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Elektronik — TV & Aksesoris", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Elektronik — Peralatan Listrik Kecil", biasaPct: 6.0, khususPct: 7.5 },
  { main: "Elektronik", label: "Elektronik — Kelistrikan", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Elektronik", label: "Elektronik — Elektronik Lainnya", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Aksesoris Konsol", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Konsol Game", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Video Game", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Gaming & Konsol — Gaming & Konsol Lainnya", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Handphone & Aksesoris — Handphone", biasaPct: 1.0, khususPct: 2.5 },
  { main: "Elektronik", label: "Handphone & Aksesoris — Tablet", biasaPct: 1.0, khususPct: 2.5 },
  { main: "Elektronik", label: "Handphone & Aksesoris — Aksesoris", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Handphone & Aksesoris — Handphone & Aksesoris Lainnya", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Handphone & Aksesoris — Kartu Perdana", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Handphone & Aksesoris — Perangkat Wearable", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Handphone & Aksesoris — Walkie Talkie", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Kamera & Drone — Aksesoris Drone", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Kamera & Drone — Aksesoris Kamera", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Kamera & Drone — Aksesoris Lensa", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Kamera & Drone — Drone", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Kamera & Drone — Kamera", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Kamera & Drone — Kamera & Drone Lainnya", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Kamera & Drone — Kamera Keamanan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Kamera & Drone — Lensa", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Kamera & Drone — Perawatan Kamera", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Desktop", biasaPct: 1.0, khususPct: 2.5 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Laptop", biasaPct: 1.0, khususPct: 2.5 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Monitor", biasaPct: 1.0, khususPct: 2.5 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Komponen Desktop & Laptop", biasaPct: 2.0, khususPct: 3.5 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Printer & Scanner", biasaPct: 2.0, khususPct: 3.5 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Penyimpanan Data", biasaPct: 3.5, khususPct: 5.0 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Peralatan Kantor", biasaPct: 3.5, khususPct: 5.0 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Aksesoris Desktop & Laptop", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Keyboard & Mouse", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Komponen Desktop & Laptop", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Komponen Network", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Komputer & Aksesoris Lainnya", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Elektronik", label: "Komputer & Aksesoris — Software", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Kamar Bayi", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Keamanan Bayi", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Kesehatan Bayi", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Kesehatan Kehamilan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Perlengkapan Ibu Hamil", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Perlengkapan Makan Bayi", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Perlengkapan Mandi", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Perlengkapan Travelling Bayi", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Popok & Pispot", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Set & Paket Hadiah", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Susu Formula & Makanan Bayi", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Ibu & Bayi — Mainan", biasaPct: 8.0, khususPct: 9.5 },
  { main: "FMCG", label: "Ibu & Bayi — Ibu & Bayi Lainnya", biasaPct: 8.0, khususPct: 9.5 },
  { main: "FMCG", label: "Kesehatan — Kesehatan Seksual", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Kesehatan — Perawatan Diri", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Kesehatan — Obat-obatan & Alat Kesehatan", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Kesehatan — Perawatan Diri", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Kesehatan — Suplemen Makanan", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Kesehatan — Kesehatan Lainnya", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Kesehatan — Perawatan Diri", biasaPct: 8.0, khususPct: 9.5 },
  { main: "FMCG", label: "Makanan & Minuman — Bahan Baking", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Bahan Pokok", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Kebutuhan Memasak", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Makanan Instan", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Makanan Ringan", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Makanan Segar & Beku", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Menu Sarapan", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Minuman", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Minuman Alkohol", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Roti & Kue", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Set Hadiah & Hampers", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Susu & Olahan", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Makanan & Minuman — Makanan & Minuman Lainnya", biasaPct: 6.0, khususPct: 7.5 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Alat Kecantikan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Kosmetik", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Paket & Set Kecantikan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Parfum & Wewangian", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan Pria", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan Rambut", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan Tangan, Kaki & Kuku", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan Tubuh", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan Wajah", biasaPct: 5.5, khususPct: 7.0 },
  { main: "FMCG", label: "Perawatan & Kecantikan — Perawatan & Kecantikan Lainnya", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Logam Mulia", biasaPct: 2.0, khususPct: 3.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Perhiasan Berharga", biasaPct: 2.0, khususPct: 3.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Aksesoris Tambahan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Aksesoris Fashion — Aksesoris Rambut", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Aksesoris Tambahan", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Anting", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Cincin", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Dasi", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Gelang Kaki", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Gelang Tangan & Bangle", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Ikat Pinggang", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Kalung", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Sarung Tangan", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Set & Paket Aksesoris", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Syal & Selendang", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Topi", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Kacamata & Aksesoris", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Aksesoris Fashion — Aksesoris Fashion Lainnya", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Aksesoris Bayi & Anak", biasaPct: 2.0, khususPct: 3.5 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Aksesoris Bayi & Anak", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Pakaian Anak Laki-Laki", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Pakaian Anak Perempuan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Pakaian Bayi", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Sepatu Anak Laki-Laki", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Sepatu Anak Perempuan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Sepatu Bayi", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Aksesoris Bayi & Anak", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Fashion Bayi & Anak — Fashion Bayi & Anak Lainnya", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Fashion", label: "Fashion Muslim — Mukena & Perlengkapan Sholat", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Fashion Muslim — Outerwear", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Fashion Muslim — Pakaian Muslim Anak", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Fashion Muslim — Pakaian Muslim Pria", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Fashion Muslim — Pakaian Muslim Wanita", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Fashion Muslim — Set", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Fashion Muslim — Pakaian Muslim Wanita", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Fashion Muslim — Fashion Muslim Lainnya", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Jam Tangan — Aksesoris Jam Tangan", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Jam Tangan — Jam Tangan Couple", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Jam Tangan — Jam Tangan Pria", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Jam Tangan — Jam Tangan Wanita", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Jam Tangan — Jam Tangan Lainnya", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Koper & Tas Travel — Aksesoris Travel", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Koper & Tas Travel — Koper", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Koper & Tas Travel — Tas Travel", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Koper & Tas Travel — Tas Travel", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Fashion", label: "Koper & Tas Travel — Koper & Tas Travel Lainnya", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Pria — Atasan", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Celana Panjang", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Celana Panjang Jeans", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Celana Pendek", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Hoodie & Sweatshirt", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Jaket, Mantel, & Rompi", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Jas Formal", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Kaos Kaki", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Kostum", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Pakaian Dalam", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Pakaian Kerja", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Pakaian Tidur", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Pakaian Tradisional", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Set Pakaian Pria", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Sweater & Cardigan", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Pria — Pakaian Pria Lainnya", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Wanita — Kaos Kaki & Stocking", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Pakaian Wanita — Atasan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Baju Hamil", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Celana Jeans", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Celana Panjang & Legging", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Celana Pendek", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Dress", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Hoodie & Sweatshirt", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Jaket, Mantel, & Rompi", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Jumpsuit, Playsuit, & Overall", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Kain", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Kostum", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Pakaian Dalam", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Pakaian Tidur & Piyama", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Pakaian Tradisional", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Rok", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Set", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Sweater & Cardigan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Wedding Dress", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Pakaian Wanita — Pakaian Wanita Lainnya", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Sepatu Pria — Aksesoris & Perawatan Sepatu", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Pria — Boot", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Pria — Loafer", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Pria — Oxford", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Pria — Sandal", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Pria — Slip-On & Mules", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Pria — Sneakers", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Pria — Sepatu Pria Lainnya", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Wanita — Aksesoris & Perawatan Sepatu", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Wanita — Boots", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Wanita — Heels", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Wanita — Sandal Jepit & Sandal Lainnya", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Wanita — Sepatu Flat", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Wanita — Sneakers", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Wanita — Wedges", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Sepatu Wanita — Sepatu Wanita Lainnya", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Fashion", label: "Tas Pria — Clutch", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Dompet", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Ransel Pria", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tas Kerja", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tas Laptop", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tas Pinggang Pria", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tas Selempang & Bahu Pria", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tote Bag", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Pria — Tas Pria Lainnya", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Aksesoris Tas", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Clutch", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Dompet Wanita", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Ransel Wanita", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Tas Laptop", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Tas Pinggang Wanita", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Tas Selempang & Bahu Wanita", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Top Handle Bag", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Tote Bag", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Fashion", label: "Tas Wanita — Tas Wanita Lainnya", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Alat Tulis", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Pembungkus Kado & Kemasan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Perlengkapan Menggambar", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Perlengkapan Sekolah & Kantor", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Surat-Menyurat", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Buku Tulis & Kertas", biasaPct: 6.0, khususPct: 7.5 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Pembungkus Kado & Kemasan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Buku & Alat Tulis — Buku & Alat Tulis Lainnya", biasaPct: 6.0, khususPct: 7.5 },
  { main: "Lifestyle", label: "Buku & Majalah — Buku Bacaan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Buku & Majalah — E-Book", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Buku & Majalah — Majalah & Koran", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Buku & Majalah — Buku Bacaan", biasaPct: 6.0, khususPct: 7.5 },
  { main: "Lifestyle", label: "Buku & Majalah — Buku Bacaan", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Buku & Majalah — Buku & Majalah Lainnya", biasaPct: 6.0, khususPct: 7.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Grooming Hewan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Pakaian & Aksesoris Hewan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Perawatan Kesehatan Hewan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Aksesoris Hewan Peliharaan", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Litter & Toilet", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Makanan Hewan", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Hewan Peliharaan — Hewan Peliharaan Lainnya", biasaPct: 6.0, khususPct: 7.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Alat & Aksesoris Musik", biasaPct: 6.0, khususPct: 7.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Album Foto", biasaPct: 6.0, khususPct: 7.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Hobi & Koleksi Lainnya", biasaPct: 6.0, khususPct: 7.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Perlengkapan Menjahit", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Lifestyle", label: "Hobi & Koleksi — CD, DVD & Bluray", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Piringan Hitam", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Souvenir & Hadiah", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Koleksi", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Hobi & Koleksi — Mainan & Games", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Mobil — Aksesoris Eksterior Mobil", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Mobil — Aksesoris Interior Mobil", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Mobil — Gantungan & Sarung Kunci Kendaraan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Mobil — Mobil", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Mobil — Oli & Pelumas Kendaraan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Mobil — Perawatan Kendaraan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Mobil — Perkakas & Perlengkapan Kendaraan", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Mobil — Suku Cadang Mobil", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Mobil — Mobil Lainnya", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Aksesoris Olahraga & Aktivitas Outdoor", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Pakaian Olahraga & Aktivitas Outdoor", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Aksesoris Olahraga & Aktivitas Outdoor", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Alat Rekreasi Olahraga & Aktivitas Outdoor", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Pakaian Olahraga & Aktivitas Outdoor", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Sepatu Olahraga", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Olahraga & Outdoor — Olahraga & Outdoor Lainnya", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Pengharum Ruangan & Aromaterapi", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Peralatan Makan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perlengkapan Dapur", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perlengkapan Keagamaan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perlengkapan Rumah Lainnya", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Dekorasi", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Furniture", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Kamar Tidur", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Lampu", biasaPct: 6.5, khususPct: 8.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Alat Pengaman", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Alat Pertukangan & Renovasi Rumah", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Kamar Mandi", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perawatan Rumah", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perlengkapan Pesta", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Taman", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Dekorasi", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Organizer Rumah", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Penghangat Tangan & Kantong Kompres", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perawatan Rumah", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Perlengkapan Rumah — Perlengkapan Dapur", biasaPct: 8.0, khususPct: 9.5 },
  { main: "Lifestyle", label: "Sepeda Motor — Aksesoris Sepeda Motor", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Sepeda Motor — Helm & Aksesoris Pengendara Motor", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Sepeda Motor — Sepeda Motor", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Sepeda Motor — Suku Cadang Motor", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Lifestyle", label: "Sepeda Motor — Sepeda Motor Lainnya", biasaPct: 7.5, khususPct: 9.0 },
  { main: "Tiket, Voucher, & Layanan", label: "Tiket, Voucher, & Layanan — Belanja", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Tiket, Voucher, & Layanan", label: "Tiket, Voucher, & Layanan — Gaming", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Tiket, Voucher, & Layanan", label: "Tiket, Voucher, & Layanan — Layanan", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Tiket, Voucher, & Layanan", label: "Tiket, Voucher, & Layanan — Listrik, Gas, & Air", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Tiket, Voucher, & Layanan", label: "Tiket, Voucher, & Layanan — Makanan & Minuman", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Tiket, Voucher, & Layanan", label: "Tiket, Voucher, & Layanan — Streaming", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Tiket, Voucher, & Layanan", label: "Tiket, Voucher, & Layanan — Telco", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Tiket, Voucher, & Layanan", label: "Tiket, Voucher, & Layanan — Tiket Event", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Tiket, Voucher, & Layanan", label: "Tiket, Voucher, & Layanan — Travel & Tour", biasaPct: 5.5, khususPct: 7.0 },
  { main: "Tiket, Voucher, & Layanan", label: "Tiket, Voucher, & Layanan — E-Money", biasaPct: 7.5, khususPct: 9.0 },
];
